[package]
name = 'digital-advertisment'
version = '1.0.0'

[addresses]
digital_advertisment = "_"
Std = "0x1"
aptos_std = "0x1"

[dependencies]
AptosFramework = { local = "../aptos-core/aptos-move/framework/aptos-framework"}